# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitbitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_id', models.CharField(max_length=6)),
                ('fitbit_access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stress', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=1024)),
                ('authority', models.CharField(choices=[('U', 'user'), ('A', 'admin')], max_length=1)),
                ('icon', models.ImageField(upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Group')),
            ],
        ),
        migrations.AddField(
            model_name='stress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.User'),
        ),
        migrations.AddField(
            model_name='fitbitaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.User'),
        ),
        migrations.AddField(
            model_name='attendancerecod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.User'),
        ),
    ]
